<?php

use Illuminate\Database\Seeder;
use App\Role;

class RoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       
        $permission = [

          "'add_registration_all'" => "on",
          "'add_registration'" => "on",
          "'view_registration'" => "on",
          "'edit_registration'" => "on",
          "'delete_registration'" => "on",
          "'add_employee_all'" => "on",
          "'add_employee'" => "on",
          "'view_employee'" => "on",
          "'edit_employee'" => "on",
          "'delete_employee'" => "on",
          "'add_company_all'" => "on",
          "'add_company'" => "on",
          "'view_company'" => "on",
          "'edit_company'" => "on",
          "'delete_company'" => "on",
          "'add_paymentType_all'" => "on",
          "'add_paymentType'" => "on",
          "'view_paymentType'" => "on",
          "'edit_paymentType'" => "on",
          "'delete_paymentType'" => "on",
          "'add_tax_all'" => "on",
          "'add_tax'" => "on",
          "'view_tax'" => "on",
          "'edit_tax'" => "on",
          "'delete_tax'" => "on",
          "'add_reason_all'" => "on",
          "'add_reason'" => "on",
          "'view_reason'" => "on",
          "'edit_reason'" => "on",
          "'delete_reason'" => "on",
          "'add_device_all'" => "on",
          "'add_device'" => "on",
          "'view_device'" => "on",
          "'edit_device'" => "on",
          "'delete_device'" => "on",
          "'add_root_all'" => "on",
          "'add_root_scheme'" => "on",
          "'view_root_scheme'" => "on",
          "'edit_root_scheme'" => "on",
          "'delete_root_scheme'" => "on",
          "'add_scheme_all'" => "on",
          "'add_scheme'" => "on",
          "'view_scheme'" => "on",
          "'edit_scheme'" => "on",
          "'delete_scheme'" => "on",
          "'add_terms_all'" => "on",
          "'add_term'" => "on",
          "'view_term'" => "on",
          "'edit_term'" => "on",
          "'delete_term'" => "on",
          "'add_inquiry_all'" => "on",
          "'add_inquiry'" => "on",
          "'view_inquiry'" => "on",
          "'edit_inquiry'" => "on",
          "'delete_inquiry'" => "on",
          "'add_confirminquiry_all'" => "on",
          "'add_confirminquiry'" => "on",
          "'view_confirminquiry'" => "on",
          "'edit_confirminquiry'" => "on",
          "'delete_confirminquiry'" => "on",
          "'add_member_all'" => "on",
          "'add_member'" => "on",
          "'view_member'" => "on",
          "'edit_member'" => "on",
          "'delete_member'" => "on",
          "'add_memberAssesment_all'" => "on",
          "'add_member_assessment'" => "on",
          "'view_member_assessment'" => "on",
          "'edit_member_assessment'" => "on",
          "'delete_member_assessment'" => "on",
          "'add_assign_all'" => "on",
          "'add_assign_renewal'" => "on",
          "'view_assign_renewal'" => "on",
          "'edit_assign_renewal'" => "on",
          "'delete_assign_renewal'" => "on",
          "'add_PT_level_all'" => "on",
          "'add_pt_level'" => "on",
          "'view_pt_level'" => "on",
          "'edit_pt_level'" => "on",
          "'delete_pt_level'" => "on",
          "'add_assign_PT_all'" => "on",
          "'add_assign_pt_level'" => "on",
          "'view_assign_pt_level'" => "on",
          "'edit_assign_pt_level'" => "on",
          "'delete_assign_pt_level'" => "on",
          "'add_PT_time_all'" => "on",
          "'add_pt_time'" => "on",
          "'view_pt_time'" => "on",
          "'edit_pt_time'" => "on",
          "'delete_pt_time'" => "on",
          "'add_matp_all'" => "on",
          "'add_matp_level'" => "on",
          "'add_member_manage_all'" => "on",
          "'add_member_manage'" => "on",
          "'view_member_manage'" => "on",
          "'edit_member_manage'" => "on",
          "'delete_member_manage'" => "on",
          "'add_claim_all'" => "on",
          "'add_claim'" => "on",
          "'view_claim'" => "on",
          "'edit_claim'" => "on",
          "'delete_claim'" => "on",
          "'add_exercise_all'" => "on",
          "'add_exercise'" => "on",
          "'view_exercise'" => "on",
          "'edit_exercise'" => "on",
          "'delete_exercise'" => "on",
          "'add_exercise_tags_all'" => "on",
          "'add_exercise_tags'" => "on",
          "'view_exercise_tags'" => "on",
          "'edit_exercise_tags'" => "on",
          "'delete_exercise_tags'" => "on",
          "'add_planworkout_all'" => "on",
          "'add_planworkout'" => "on",
          "'view_planworkout'" => "on",
          "'edit_planworkout'" => "on",
          "'delete_planworkout'" => "on",
          "'add_planview_all'" => "on",
          "'add_planview'" => "on",
          "'view_planview'" => "on",
          "'edit_planview'" => "on",
          "'delete_planview'" => "on",
          "'add_assign_workout_all'" => "on",
          "'add_assign_workout'" => "on",
          "'view_assign_workout'" => "on",
          "'edit_assign_workout'" => "on",
          "'delete_assign_workout'" => "on",
          "'add_measurement_all'" => "on",
          "'add_measurement'" => "on",
          "'view_measurement'" => "on",
          "'edit_measurement'" => "on",
          "'delete_measurement'" => "on"     ];

            $s=serialize($permission);

		      Role::create([

		       'employeerole' => 'admin_new',
		       'path' => '',
		       'permission' => $s,
		       'description' => 'admin',
		       'status' => 1
		    ]);
    }
}
