 <select type="time" class="form-control" name="working_hour_from_1" id="fromtime" required="">
               <option value="06:00" @if(old( 'working_hour_from_1')=='06:00' ) selected @endif @if($memberdata->working_hour_from_1) {{ $memberdata->working_hour_from_1 =='06:00' ? 'selected' : ''}}  @endif>06:00 AM</option>
               <option value="07:00" @if(old( 'working_hour_from_1')=='07:00' ) selected @endif @if($memberdata->working_hour_from_1) {{ $memberdata->working_hour_from_1 =='07:00' ? 'selected' : ''}}  @endif >07:00 AM</option>
               <option value="08:00" @if(old( 'working_hour_from_1')=='08:00' ) selected @endif @if($memberdata->working_hour_from_1) {{ $memberdata->working_hour_from_1 =='08:00' ? 'selected' : ''}}  @endif >08:00 AM</option>
               <option value="09:00" @if(old( 'working_hour_from_1')=='09:00' ) selected @endif @if($memberdata->working_hour_from_1) {{ $memberdata->working_hour_from_1 =='09:00' ? 'selected' : ''}}  @endif >09:00 AM</option>
               <option value="10:00" @if(old( 'working_hour_from_1')=='10:00' ) selected @endif @if($memberdata->working_hour_from_1) {{ $memberdata->working_hour_from_1 =='10:00' ? 'selected' : ''}}  @endif >10:00 AM</option>
               <option value="11:00" @if(old( 'working_hour_from_1')=='11:00' ) selected @endif @if($memberdata->working_hour_from_1) {{ $memberdata->working_hour_from_1 =='11:00' ? 'selected' : ''}}  @endif >11:00 AM</option>
               <option value="12:00" @if(old( 'working_hour_from_1')=='12:00' ) selected @endif @if($memberdata->working_hour_from_1) {{ $memberdata->working_hour_from_1 =='12:00' ? 'selected' : ''}}  @endif >12:00 PM</option>
               <option value="13:00" @if(old( 'working_hour_from_1')=='13:00' ) selected @endif @if($memberdata->working_hour_from_1) {{ $memberdata->working_hour_from_1 =='13:00' ? 'selected' : ''}}  @endif >01:00 PM</option>
               <option value="14:00" @if(old( 'working_hour_from_1')=='14:00' ) selected @endif @if($memberdata->working_hour_from_1) {{ $memberdata->working_hour_from_1 =='14:00' ? 'selected' : ''}}  @endif >02:00 PM</option>
               <option value="15:00" @if(old( 'working_hour_from_1')=='15:00' ) selected @endif @if($memberdata->working_hour_from_1) {{ $memberdata->working_hour_from_1 =='15:00' ? 'selected' : ''}}  @endif >03:00 PM</option>
               <option value="16:00" @if(old( 'working_hour_from_1')=='16:00' ) selected @endif @if($memberdata->working_hour_from_1) {{ $memberdata->working_hour_from_1 =='16:00' ? 'selected' : ''}}  @endif >04:00 PM</option>
               <option value="17:00" @if(old( 'working_hour_from_1')=='17:00' ) selected @endif @if($memberdata->working_hour_from_1) {{ $memberdata->working_hour_from_1 =='17:00' ? 'selected' : ''}}  @endif >05:00 PM</option>
               <option value="18:00" @if(old( 'working_hour_from_1')=='18:00' ) selected @endif @if($memberdata->working_hour_from_1) {{ $memberdata->working_hour_from_1 =='18:00' ? 'selected' : ''}}  @endif >06:00 PM</option>
               <option value="19:00" @if(old( 'working_hour_from_1')=='19:00' ) selected @endif @if($memberdata->working_hour_from_1) {{ $memberdata->working_hour_from_1 =='19:00' ? 'selected' : ''}}  @endif >07:00 PM</option>
               <option value="20:00" @if(old( 'working_hour_from_1')=='20:00' ) selected @endif @if($memberdata->working_hour_from_1) {{ $memberdata->working_hour_from_1 =='20:00' ? 'selected' : ''}}  @endif >08:00 PM</option>
               <option value="21:00" @if(old(working_hour_from_1')=='21:00' ) selected @endif @if($memberdata->working_hour_from_1) {{ $memberdata->working_hour_from_1 =='21:00' ? 'selected' : ''}}  @endif >09:00 PM</option>
               <option value="22:00" @if(old( 'working_hour_from_1')=='22:00' ) selected @endif @if($memberdata->working_hour_from_1) {{ $memberdata->working_hour_from_1 =='22:00' ? 'selected' : ''}}  @endif >10:00 PM</option>